### ISSUE TITLE
Connection failed while trying to connect to timescaledb in pgAdmin4

### ISSUE THREAD

**Issue by djwafelap** [Expaso/hassos-addon-pgadmin4#11]
# Problem/Motivation
Connection to DB failed

## Expected behavior
Connection to DB server in pgAdmin4.

## Actual behavior
Error Message:
"connection failed: connection to server at "192.168.1.127", port 5432 failed: Connection refused Is the server running on that host and accepting TCP/IP connections?"

## Steps to reproduce
After successfully starting timescaledb (“NOTICE: TimescaleDb is running!”) I tried to establish a connection to the server via pgAdmin4 according to the instructions:
Host: HA IP adress
Port: 5432
Maintenance DB: homeassistant
Username: postgres
Password: homeassistant

Can anyone help??? Where can i find pg_hba.conf to check if connections are accepted???

**Comment by djwafelap** [comment]
just to add information:
i am running Hassio and core newest versions as virtual machine on proxmox. but the addon is installed on the hassio machine.

**Comment by expaso** [comment]
By default,  the addon is not listening on external IP addresses. You can change this behaviour by opening the 5432 port in the settings screen of the addon.

If your goal is to just connect with the pgAdmin addon, to the TimescaleDB addon running both on the same HASSIO, you don't need to open-up this port, but just use the internal hostname of the Timescaledb addon:

You can use these settings:

![image](https://github.com/user-attachments/assets/2bf2294b-e93c-4664-b6f6-ea059ab77fbb)


Ofcourse you need to use your own password. The default password is "homeassistant" after installing the addon. I advice you to change that password, even though the TimescaleDb addon is not exposed to your LAN by default.

**Comment by expaso** [comment]
@djwafelap  Is your issue resolved with the above?

**Comment by djwafelap** [comment]
> v

Hi,
sorry for my late answer. Yes, that hostname worked fine!
Thanks a lot!

**Comment by djwafelap** [comment]
resolved!
