### ISSUE TITLE
Can't install on RPi4 

### ISSUE THREAD

**Issue by m-l** [Expaso/hassos-addon-pgadmin4#5]
There's the error when trying to instal or upgrade on RPi 4 (Home Assistant 2022.11.2 on Raspian+Docker): 
`Can't install husselhans/hassos-addon-pgadmin4-armv7:2.1.1: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=2.1.1&fromImage=husselhans%2Fhassos-addon-pgadmin4-armv7&platform=linux%2Farm%2Fv7: Not Found ("manifest for husselhans/hassos-addon-pgadmin4-armv7:2.1.1 not found: manifest unknown: manifest unknown")`

**Comment by expaso** [comment]
Hmmm. I will look into this. One thing though, the RPI 4 should be aarch64 and not armv7. Are you sure this is a PI 4?

**Comment by m-l** [comment]
Of course:
<img width="358" alt="image" src="https://user-images.githubusercontent.com/5484460/201512704-6935abc8-4af2-493c-a84f-998bd3fec0ae.png">

I use Home Assistant 32-bit version as it is more stable.

**Comment by expaso** [comment]
I see that the images for armv7 indeed are not created. I'm looking into this.

Albeit, since a few years, the 64-bit is the recommended version for HASSOS on the RPI4, and at least I have no issues there..

**Comment by m-l** [comment]
Thanks!

Well I use HA supervised on regular Raspbian. HASSOS is too limiting for me as I also need regular Rasbpian local dev environment with gcc+some libs, because in addition to HA I run a couple of my own processes.

**Comment by top4ek** [comment]
Got that too. RPi4 with 4GB, so it don't require 64 bit. And back then 64 bit version was quite unstable.

**Comment by Pannnenkoek** [comment]
I appear to have the same issue, RPi 3 32-bit running Hassio:  Home Assistant 2022.12.1 Supervisor 2022.11.2 Operating System 9.3 Frontend-versie: 20221208.0 - latest 

`Can't install husselhans/hassos-addon-pgadmin4-armv7:2.1.1: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=2.1.1&fromImage=husselhans%2Fhassos-addon-pgadmin4-armv7&platform=linux%2Farm%2Fv7: Not Found ("manifest for husselhans/hassos-addon-pgadmin4-armv7:2.1.1 not found: manifest unknown: manifest unknown")`

**Comment by expaso** [comment]
I'm still working for you guys, but this aint trivial.. Al lot of stuff nowadays won't compile nicely on 32 bit, so it's a lot of manual work..

**Comment by expaso** [comment]
FINALLY!! 

Update 3.0.1 ws jsut released, containing pgAdmin4 8.2, and supporting this architecture again.
I apologize for the long waiting.. I don't have a lot of free time on my hands, but at least I haven't forgotten ;)

Enjoy the release!
