### ISSUE TITLE
addon won't load

### ISSUE THREAD

**Issue by syntax-error1978** [Expaso/hassos-addon-pgadmin4#8]
Hi all,

After a crash and rollback yesterday my addon won't startup anymore.
tried to reinstall but nothing works.

here are the logs:
I think the last two lines have something to do with it but I have no idea what that is. never installed nginx

Thanks in advance!

pgAdmin4
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/00-banner.sh
-----------------------------------------------------------
 Add-on: pgAdmin4
 A PostgreSQL Management and Query tool
-----------------------------------------------------------
 Add-on version: 2.1.1
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.5  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2023.2.3
 Home Assistant Supervisor: 2023.01.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
cont-init: info: running /etc/cont-init.d/nginx.sh
cont-init: info: /etc/cont-init.d/nginx.sh exited 0
cont-init: info: running /etc/cont-init.d/pgadmin4.sh
cont-init: info: /etc/cont-init.d/pgadmin4.sh exited 0
cont-init: info: running /etc/cont-init.d/user.sh
cont-init: info: /etc/cont-init.d/user.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun nginx (no readiness notification)
services-up: info: copying legacy longrun pgadmin4 (no readiness notification)
s6-rc: info: service legacy-services successfully started
[11:35:18] INFO: Starting pgAdmin..
[11:35:39] INFO: Waiting for pgadmin to become available..
.
.
.
.
.
.
.
.
.
[2023-02-10 11:35:43 +0100] [356] [INFO] Starting gunicorn 20.1.0
[2023-02-10 11:35:43 +0100] [356] [INFO] Listening at: unix:/tmp/pgadmin4.sock (356)
[2023-02-10 11:35:43 +0100] [356] [INFO] Using worker: gthread
[2023-02-10 11:35:43 +0100] [375] [INFO] Booting worker with pid: 375
[11:35:43] INFO: Starting NGinx...
[11:35:43] NOTICE: pgAdmin is running.
[11:35:43] NOTICE: pgAdmin4 is ready to accept connections.
nginx: [warn] lua_load_resty_core is deprecated (the lua-resty-core library is required since ngx_lua v0.10.16) in /etc/nginx/nginx.conf:43

**Comment by expaso** [comment]
This looks fine. Still an issue?
