### ISSUE TITLE
Pleade update PGAdmin to Version 7.6

### ISSUE THREAD

**Issue by coreGreenberet** [Expaso/hassos-addon-pgadmin4#9]
Hello,

this addon is currently using PGAdmin 6.15 which is almost a year old ( 20 October 2022 ) and 13 versions behind the latest.

Thanks

**Comment by expaso** [comment]
It took a while, but here you go!
https://github.com/Expaso/hassos-addons/pull/37

Version 3.0.1 was just released, which contains the pgAdmin 8.2.
